### PR TITLE
Replace usage of strings.h with string.h #8

### LINKED ISSUE #8: Missing dependency "strings.h: No such file or directory"
**Describe the bug**
On AVR Mega devices the `strings.h` file can not be found and therefore not included, which makes compilation fail.

**To Reproduce**
1. Compile on AVR Mega

**Expected behavior**
No compilation error

**Additional context**
 The aforementioned file is included in the `mbedtls_debug.c` file on line 15 and is only used for the [`rindex`](https://pubs.opengroup.org/onlinepubs/007908775/xsh/rindex.html) method. Which is not recommeded anyway, because we can simply use the cross-plattform [`strrchr`](https://pubs.opengroup.org/onlinepubs/007908775/xsh/strrchr.html) method from `string.h` instead.

### PR DESCRIPTION
**Pull request by MathewHDYT**
Fixes #8 @lakshanthad would be nice if this could be reviewed and merged to make this library usable for even more boards without much change.

### CODE REVIEW

**Comment by LynnL4** [comment]
Thanks for the pr. it looks great.

**Comment by MathewHDYT** [comment]
Would be nice if the change could also be relaesed as a new version on GitHub `v3.0.2`

**Comment by MathewHDYT** [comment]
@lakshanthad, @LynnL4 Would be highly appreciated if the current state of the version could be released, so that the fix can be downloaded over the Arduino IDE as well.

**Comment by MathewHDYT** [comment]
@lakshanthad, @LynnL4 Would be nice if this could be released as a new version on GitHub `v3.0.2`. Because curerntly there is still now way to download the changes over the Arduino IDE directly.

**Comment by MathewHDYT** [comment]
@LynnL4, @lakshanthad, @MatthewJeffson Would be nice if this could be released as a new version on GitHub as `v3.0.2`. Because curerntly there is still now way to download the changes over the Arduino IDE directly.

**Pull request merged**
